### ISSUE TITLE
Aplicação do nome "Open School Brasil"

### ISSUE THREAD

**Issue by kvnol** [openschoolbr/design#1]
Como primeira issue do repositório de design, é extremamente importante definirmos como vamos aplicar o nome da escola nas comunidades, redes e em citações.

Eu acredito que a aplicação "**Open School**" separado é melhor aplicado do que "**OpenSchool**" mais por questões de estética, já aplicado no conceito do logotipo do que por algum motivo mais técnico, mas gostaria de saber a opinião de vocês.

**Comment by muniz95** [comment]
Concordo. Eu coloquei tudo junto mais por influência da Webschool (que de certa forma foi a faísca pra começarmos essa org).
Da minha parte prefiro "Open School" a "OpenSchool" também.

**Comment by kvnol** [comment]
@muniz95 Maravilha! Eu tinha imaginado isso.

**Comment by angelilton** [comment]
tenho uma opção para a logo ainda está aberta?

**Comment by kvnol** [comment]
Puts, @angelilton, nós estávamos discutindo [nessa issue no fórum](https://github.com/openschoolbr/forum/issues/3), mas a galera curtiu a primeira proposta e encerramos a issue e aplicamos ela nas redes.

**Comment by kvnol** [comment]
É importante ressaltar também que "A Open School" é necessário ser utilizado, pois estamos tratando de uma escola, ao invés de "O Open School". :heart:

**Comment by khaosdoctor** [comment]
Eu prefiro "Open School" separado, e como sigla acho que OS-Br seria legal também

**Comment by larismourullo** [comment]
Como já foi decidido estou fechando a issue, caso seja necessário só abrir novamente.
