### ISSUE TITLE
Definição da descrição da Open School Brasil

### ISSUE THREAD

**Issue by kvnol** [openschoolbr/design#2]
Estava para abrir essa discussão, mas a @larismourullo cobrou e virou imediato (:smile:). Mas então, precisamos definir a descrição curta (uma espécie de slogan) para a Open School e seria interessante ver as sugestões de vocês, a mais votada será definida.

Uma dica: é interessante ser algo de até 120 caracteres. :heart:

**Comment by larismourullo** [comment]
Se possível colocando: "feita pela comunidade para a comunidade." Porque esse é o nosso objetivo e foco ❤️ 😍

**Comment by kvnol** [comment]
Puts, @larismourullo, acho isso ótimo!

**Comment by alinebastos** [comment]
Era mais ou menos a definição que eu estava usando ontem:
"Uma escola aberta, da comunidade, para a comunidade!"

**Comment by kvnol** [comment]
A da @alinebastos é ótima, porque cita a escola e ainda fica curto. Podemos fechar nessa? :heart_eyes:

**Comment by muniz95** [comment]
Por mim tá excelente!

**Comment by kvnol** [comment]
Maravilha!

**Comment by larismourullo** [comment]
@alinebastos brilhou ✨
